name: epickitchens
channels:
  - pytorch-lts
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - av
  - cudatoolkit==11.1.74
  - matplotlib
  - numpy
  - pip
  - python==3.8
  - pytorch==1.8.2
  - tensorboard
  - torchvision==0.9.2
  - simplejson
  - scikit-learn
  - psutil
  - tqdm
  - timm
  - pandas
  - Pillow
  - pytorch-lightning
  - ipywidgets
  - pip:
    - fvcore
    - opencv-python
    - pytorchvideo==0.1.3
    - yacs==0.1.8
    - git+https://github.com/facebookresearch/TimeSformer.git
    - https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.8/detectron2-0.6%2Bcu111-cp38-cp38-linux_x86_64.whl
    - git+https://github.com/fran6co/slowfast.git@4de0e9e9cf51678800661b78da740f26f9192aca
    - onnxruntime-gpu
